version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    # Disable version updates and only allow security updates
    open-pull-requests-limit: 0
    # TODO(PT-1887): Enable reviewers when application has been transferred to Ratkaisutoimisto
    #reviewers:
    #  - "City-of-Helsinki/ratkaisutoimiston-frontend"
