include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 80

# Build image for deployment
build-review:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'review'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://tunnistamo.test.kuva.hel.ninja'
    # Temporarily use tapahtumat api proxy to get linkedevents data
    DOCKER_BUILD_ARG_REACT_APP_API_URI: 'https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql'
  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'staging'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://tunnistamo.test.kuva.hel.ninja'
    # Temporarily use tapahtumat api proxy to get linkedevents data
    DOCKER_BUILD_ARG_REACT_APP_API_URI: 'https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql'
  only:
    refs:
      - develop

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'production'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://tunnistamo.test.kuva.hel.ninja'
    # Temporarily use tapahtumat api proxy to get linkedevents data
    DOCKER_BUILD_ARG_REACT_APP_API_URI: 'https://tapahtumat-proxy.test.kuva.hel.ninja/proxy/graphql'
  only:
    refs:
      - /^release-.*$/

# Deploy built image
review:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'

staging:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
  only:
    refs:
      - develop

production:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
