#
# Test pipeline. Run build and deploy for Platta test environments. 
# Pipeline runs different tests e.g. unittest and browser tests.
#
# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
# only PR trigger pipeline
trigger: none

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is 
# opened with one of the specified target branches, or when updates are made to 
# such a pull request.
#
# GitHub creates a new ref when a pull request is created. The ref points to a 
# merge commit, which is the merged code between the source and target branches 
# of the pull request.
#
# Opt out of pull request validation 
pr:
  # PR target branch
  branches:
    include:
    - master
  paths:
    exclude:
    - '*release-please*'
    - '**/*.md'
    - '.github/'
    - 'azure-pipelines-release.yml'
    - 'azure-pipelines-test.yml'
    - 'docker-compose*'

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
  # Azure DevOps repository
  - repository: kultus-pipelines
    type: git
    ref: refs/heads/tunnistamo_review
    # Azure DevOps project/repository
    name: kultus/kultus-pipelines

extends:
  # Filename in Azure DevOps Repository (note possible -ui or -api)
  # Django example: azure-pipelines-PROJECTNAME-api-release.yml
  # Drupal example: azure-pipelines-drupal-release.yml
  template: azure-pipelines-kultus-admin-ui-review.yml@kultus-pipelines
  parameters:
    # Application build arguments and config map values as key value pairs.
    # Does not contain all buildArguments, the rest located in kultus-pipelines/kultus-admin-ui-development.yml and kultus-admin-ui-common.yml
    # The values here will override the values defined in the harrastukset-pipelines repository.
    buildArgs:
      REACT_APP_API_URI: 'https://kultus-local.api.dev.hel.ninja/graphql'
      REACT_APP_API_REPORT_URI: 'https://kultus-local.api.dev.hel.ninja/reports'

      REACT_APP_LINKEDEVENTS_API_URI: 'https://api.hel.fi/linkedevents-test/v1'

    # FIXME: The kultus.hkih -server responded several days with gateway timeout and internal server error, 
    # so it was changed to the production cms.
    # REACT_APP_CMS_URI: 'https://kultus.hkih.stage.geniem.io/graphql'
      REACT_APP_CMS_URI: 'https://kultus.content.api.hel.fi/graphql'

    # configMap: # pod environment variables