version: '3.7'

services:
  app:
    container_name: palvelutarjotin-admin
    env_file: .env
    build:
      context: .
      args:
        REACT_APP_API_REPORT_URI: ${REACT_APP_API_REPORT_URI}
        REACT_APP_API_URI: ${REACT_APP_API_URI}
        REACT_APP_APPLICATION_NAME: ${REACT_APP_APPLICATION_NAME}
        REACT_APP_CMS_URI: ${REACT_APP_CMS_URI}
        REACT_APP_ENVIRONMENT: ${REACT_APP_ENVIRONMENT}
        REACT_APP_LINKEDEVENTS_API_URI: ${REACT_APP_LINKEDEVENTS_API_URI}
        REACT_APP_OIDC_AUTHORITY: ${REACT_APP_OIDC_AUTHORITY}
        REACT_APP_OIDC_CLIENT_ID: ${REACT_APP_OIDC_CLIENT_ID}
        REACT_APP_OIDC_SCOPE: ${REACT_APP_OIDC_SCOPE}
        REACT_APP_ORIGIN: ${REACT_APP_ORIGIN}
        REACT_APP_SENTRY_DSN: ${REACT_APP_SENTRY_DSN}
        REACT_APP_VERSION: ${REACT_APP_VERSION}
    ports:
      - '3000:8080'
      