name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      VITE_APP_ORIGIN: http://localhost:8080
      PORT: 8080
      NODE_ENV: production
      VITE_APP_API_URI: https://kultus.api.test.hel.ninja/graphql
      VITE_APP_CMS_URI: https://kultus.app-staging.hkih.hion.dev/graphql
      VITE_APP_LINKEDEVENTS_API_URI: https://linkedevents.api.test.hel.ninja/v1
      VITE_APP_API_REPORT_URI: https://kultus.api.test.hel.ninja/reports
      VITE_APP_HELSINKI_PROFILE_URL: https://profiili.test.hel.ninja/loginsso
      VITE_APP_OIDC_API_CLIENT_ID: kultus-api-test
      VITE_APP_OIDC_AUDIENCES: "kultus-api-test,profile-api-test"
      VITE_APP_OIDC_AUTHORITY: https://tunnistus.test.hel.ninja/auth/realms/helsinki-tunnistus
      VITE_APP_OIDC_AUTOMATIC_SILENT_RENEW_ENABLED: 0
      VITE_APP_OIDC_CLIENT_ID: kultus-admin-ui-test
      VITE_APP_OIDC_RETURN_TYPE: code
      VITE_APP_OIDC_SCOPE: "openid profile email"
      VITE_APP_OIDC_SERVER_TYPE: KEYCLOAK
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Build production application
      run: yarn build
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn test:browser:ci
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
